import StyleDictionary from 'style-dictionary';
import { createPropertyFormatter } from 'style-dictionary/utils';

/** Builds a `--rythm-...` custom property name straight from the token's JSON path. */
function rythmName(token: { path: string[] }) {
  return ['rythm', ...token.path].join('-');
}

const sd = new StyleDictionary({
  source: ['src/**/*.json'],
  hooks: {
    transforms: {
      // `--rythm-<path>`, computed directly from the token's path so irregular
      // segments (e.g. the Utopia `step.-2` negative index) survive untouched.
      'name/rythm': {
        type: 'name',
        transform: rythmName,
      },
    },
    formats: {
      // Single hand-rolled format: groups every token by its `$extensions.rythm`
      // metadata into the four @layer blocks + tag-scoped component selectors
      // described in docs/superpowers/specs/2026-06-22-token-pipeline-and-component-tokens-design.md
      'css/rythm': ({ dictionary, options }) => {
        const usesDtcg = options.usesDtcg ?? true;
        const formatAt = (spaces: number) =>
          createPropertyFormatter({
            outputReferences: options.outputReferences ?? true,
            dictionary,
            format: 'css',
            formatting: { indentation: ' '.repeat(spaces), commentStyle: 'none' },
            usesDtcg,
          });
        const format4 = formatAt(4);
        const format6 = formatAt(6);

        // Style Dictionary resolves `{refs}` in every string it finds, including
        // inside `$extensions` — except under a key literally named `original`.
        // So a dark/reduced-motion override authored as `{color.neutral-800}`
        // would already be flattened to a literal by the time we get here. Dark
        // variants are therefore authored as real (hidden) sibling tokens, which
        // *do* get the raw-preserving `original.$value` treatment; `darkRef`
        // just points at that sibling's dotted path.
        const byPath = new Map(dictionary.allTokens.map((t) => [t.path.join('.'), t]));

        const primitives: any[] = [];
        const scales: any[] = [];
        const semantic: any[] = [];
        const componentsBySelector = new Map<string, any[]>();

        for (const token of dictionary.allTokens) {
          const ext = token.$extensions?.rythm;
          if (ext?.hidden) {
            continue;
          } else if (ext?.selector) {
            const group = componentsBySelector.get(ext.selector) ?? [];
            group.push(token);
            componentsBySelector.set(ext.selector, group);
          } else if (ext?.layer === 'semantic') {
            semantic.push(token);
          } else if (ext?.layer === 'scales') {
            scales.push(token);
          } else {
            primitives.push(token);
          }
        }

        // Reduced-motion overrides are always plain literals (e.g. "0ms"), never
        // references, so no lookup indirection is needed for those.
        const reducedMotionTokens = primitives.filter(
          (t) => t.$extensions?.rythm?.reducedMotion !== undefined,
        );
        const darkPairs = semantic
          .filter((t) => t.$extensions?.rythm?.darkRef !== undefined)
          .map((t) => ({ name: t.name, dark: byPath.get(t.$extensions.rythm.darkRef) }));

        const declare = (formatter: (t: any) => string, tokens: any[]) =>
          tokens.map(formatter).join('\n');
        const declareReducedMotion = (formatter: (t: any) => string, tokens: any[]) =>
          tokens
            .map((t) => ({
              ...t,
              value: usesDtcg ? t.value : t.$extensions.rythm.reducedMotion,
              $value: usesDtcg ? t.$extensions.rythm.reducedMotion : t.$value,
              original: {
                ...t.original,
                value: usesDtcg ? t.original.value : t.$extensions.rythm.reducedMotion,
                $value: usesDtcg ? t.$extensions.rythm.reducedMotion : t.original.$value,
              },
            }))
            .map(formatter)
            .join('\n');
        const declareDark = (formatter: (t: any) => string, pairs: { name: string; dark: any }[]) =>
          pairs.map(({ name, dark }) => formatter({ ...dark, name })).join('\n');

        const header =
          '/* Rythm Design System tokens.css — generated by Style Dictionary, do not edit directly. */\n\n';

        const sections: string[] = [];

        sections.push('@layer rythm.primitives, rythm.scales, rythm.semantic, rythm.component;');

        let primitivesLayer = `@layer rythm.primitives {\n  :root {\n${declare(format4, primitives)}\n  }`;
        if (reducedMotionTokens.length > 0) {
          primitivesLayer += `\n\n  @media (prefers-reduced-motion: reduce) {\n    :root {\n${declareReducedMotion(format6, reducedMotionTokens)}\n    }\n  }`;
        }
        primitivesLayer += '\n}';
        sections.push(primitivesLayer);

        sections.push(`@layer rythm.scales {\n  :root {\n${declare(format4, scales)}\n  }\n}`);

        let semanticLayer = `@layer rythm.semantic {\n  :root {\n${declare(format4, semantic)}\n  }`;
        if (darkPairs.length > 0) {
          semanticLayer += `\n\n  [data-theme="dark"] {\n${declareDark(format4, darkPairs)}\n  }`;
          semanticLayer += `\n\n  @media (prefers-color-scheme: dark) {\n    :root:not([data-theme="light"]) {\n${declareDark(format6, darkPairs)}\n    }\n  }`;
        }
        semanticLayer += '\n}';
        sections.push(semanticLayer);

        let componentLayer = '@layer rythm.component {';
        for (const [selector, tokens] of componentsBySelector) {
          componentLayer += `\n  ${selector} {\n${declare(format4, tokens)}\n  }\n`;
        }
        componentLayer += '}';
        sections.push(componentLayer);

        return header + sections.join('\n\n') + '\n';
      },
    },
  },
  platforms: {
    css: {
      transforms: ['name/rythm'],
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/rythm',
          options: {
            outputReferences: true,
          },
        },
      ],
    },
  },
});

await sd.buildAllPlatforms();

console.log('\n✅  @rythm-ds/tokens built successfully\n');
